const InformationActionTypes = {
  FETCH_INFORMATION_START: "FETCH_INFORMATION_START",
  FETCH_INFORMATION_SUCCESS: "FETCH_INFORMATION_SUCCESS",
  FETCH_INFORMATION_FAILURE: "FETCH_INFORMATION_FAILUE",
};

export default InformationActionTypes;
